### ISSUE TITLE
Run HoloOcean 1.0.0 in Docker or WSL

### ISSUE THREAD

**Issue by Jayzhang2333** [byu-holoocean/holoocean-docs#6]
Hi there,

I was trying to run HoloOcean 1.0.0 inside docker or WSL as I need to use the[ ROS2 wrapper,](https://github.com/migeran/holoocean_tools) which needs ROS2 Iron and it cannot run on ubuntu20.04. 
I both docker container or WSL, when i tried to run holoocean.make("xxxx"), it always ran into error like:
`Traceback (most recent call last):
  File "/home/jay/.local/lib/python3.10/site-packages/holoocean/environments.py", line 863, in __linux_start_process__
    loading_semaphore.acquire(30)
posix_ipc.BusyError: Semaphore is busy

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jay/.local/lib/python3.10/site-packages/holoocean/holoocean.py", line 103, in make
    return HoloOceanEnvironment(**param_dict)
  File "/home/jay/.local/lib/python3.10/site-packages/holoocean/environments.py", line 175, in __init__
    self.__linux_start_process__(
  File "/home/jay/.local/lib/python3.10/site-packages/holoocean/environments.py", line 865, in __linux_start_process__
    raise HoloOceanException(
holoocean.exceptions.HoloOceanException: Timed out waiting for binary to load. Ensure that holoocean is not being run with root priveleges.`

When I am using docker, I am 100% sure that I did not run with root priveleges and I received the same thing even with WSL. I saw when moving from HoloOcean 0.5.0 to 1.0.0, the docker support is no longer there. The [ROS wrapper](https://github.com/migeran/holoocean_tools) is also and still linking to HoloOcean 0.5.0.  I also suspect it might be some changes from Epic Game, rather than HoloOcean.

Anyway, were anyone able to run HoloOcean inside docker?

**Comment by Jayzhang2333** [comment]
I just find out BYU is also developing a [ROS wrapper](https://github.com/byu-holoocean/holoocean-ros/commits/main/), but it seems like it is still under development. I'll try the dockerfile in this repo to see if i can get holoocean working in docker

**Comment by Jayzhang2333** [comment]
I tried that dockerfile, but I still cannot run holoocean in docker. It shows the same error.

**Comment by BradenMeyers** [comment]
Hello, Can you please describe what kind of system you are trying to run this on? 
Windows, Linux, WSL? 
Currently the docker file should only work on a linux host system becasue of the host system configuration you have to run
The ROS2 wrapper is being worked on at the moment as well as the docker setup. We are still working on documenting but it works on our computers

**Comment by Jayzhang2333** [comment]
Hi Braden, I was working on a host system of Ubuntu20.04 with a base docker image of Ubuntu22. I also tried on windows with WSL (ubuntu 22). I can only run holoocean with graphic off

**Comment by BradenMeyers** [comment]
It sounds like it could be a problem with the docker container not having access to the gpu or screen. I have not had success with WSL and know the nvidia container toolkit does not support windows yet. 

Can you explain your gpu setup? On Linux you can get driver information with nvidia-smi command. 

Can you also tell me about what docker run command or docker compose to start the container. Any volumes or flags?

**Comment by BradenMeyers** [comment]
https://github.com/byu-holoocean/holoocean-ros/blob/main/ros_container/Holoocean%20Setup%20Instructions

You can ignore the parts about ros2 setup but there are some information about my setup.
